### ISSUE TITLE
1710Contigo核心BUG反馈

### ISSUE THREAD

**Issue by benr233** [stiven-ding/DeathPenalty#1]
首先是配置里的经验掉落一直改不了，无论我是改的百分比还是固定数值都会被重置为10%
其次是物品掉落这一块报错了（报错1），金币掉落也没有反应，甚至提示都没有触发，感谢
重置者接坑，希望能够修复一下以上问题，下面我贴上报错信息：
[12:15:53] [Server thread/INFO]: [DeathPenalty] Drop list got after 6 times
[12:15:53] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to DeathPenalty v${project.version}
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:383) [CraftEventFactory.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:562) [mw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1153) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:668) [mw.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:196) [CraftLivingEntity.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:181) [CraftLivingEntity.class:1.7.10-1614.UNOFFICIAL]
	at com.earth2me.essentials.PlayerExtension.damage(PlayerExtension.java:16) [Essentials.jar:?]
	at com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.java:21) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:149) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:382) [Essentials.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoSuchFieldError: SPLASH_POTION
	at com.meowj.langutils.lang.LanguageHelper.getItemName(LanguageHelper.java:68) ~[?:?]
	at com.meowj.langutils.lang.LanguageHelper.getItemDisplayName(LanguageHelper.java:45) ~[?:?]
	at net.sfcraft.plugins.deathpenalty.listener.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	... 29 more

**Comment by stiven-ding** [comment]
Thank you for your feedback.

The reloaded version of the plugin is tested ONLY on Spigot / Paper 1.12.2, and the plugin is based on Spigot API version 1.9. 

So I am sorry to say if you want it to run on your server, you may have to improve the compatibility yourself; if you have done so, welcome to pull request and I will give my thanks from the bottom of my heart.
